[project]
name = "langgraph-basic-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "langchain[openai]>=0.3.26",
    "langgraph>=0.5.4",
]
